#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 16 19:25:54 2019

@author: Kent Evans

"""

import torch
import matplotlib.pyplot as plt
import torchvision as tv
import numpy as np
